-- Dracula — ported from dracula-theme.theme-dracula VS Code
local M = {}

M.base_30 = {
  white          = "#F8F8F2",
  darker_black   = "#1e2030",
  black          = "#282A36",
  black2         = "#2e3040",
  one_bg         = "#343746",
  one_bg2        = "#3e4052",
  one_bg3        = "#44475A",
  grey           = "#6272A4",
  grey_fg        = "#6272A4",
  grey_fg2       = "#7b82b8",
  light_grey     = "#bfc1d0",
  red            = "#FF5555",
  baby_pink      = "#FF79C6",
  pink           = "#FF79C6",
  line           = "#44475A",
  green          = "#50FA7B",
  vibrant_green  = "#69ff8c",
  nord_blue      = "#8BE9FD",
  blue           = "#8BE9FD",
  yellow         = "#F1FA8C",
  sun            = "#f3fb9e",
  purple         = "#BD93F9",
  dark_purple    = "#a679e6",
  teal           = "#8BE9FD",
  orange         = "#FFB86C",
  cyan           = "#8BE9FD",
  statusline_bg  = "#21222C",
  lightbg        = "#343746",
  pmenu_bg       = "#BD93F9",
  folder_bg      = "#8BE9FD",
}

M.base_16 = {
  base00 = "#282A36",
  base01 = "#343746",
  base02 = "#3e4052",
  base03 = "#44475A",
  base04 = "#6272A4",
  base05 = "#F8F8F2",
  base06 = "#F8F8F2",
  base07 = "#FFFFFF",
  base08 = "#FF79C6",
  base09 = "#FFB86C",
  base0A = "#BD93F9",
  base0B = "#50FA7B",
  base0C = "#8BE9FD",
  base0D = "#8BE9FD",
  base0E = "#BD93F9",
  base0F = "#F1FA8C",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_30.white },
    ["@variable.builtin"] = { fg = M.base_30.pink },
    ["@variable.parameter"] = { fg = M.base_30.orange },
    ["@keyword"] = { fg = M.base_30.purple },
    ["@keyword.function"] = { fg = M.base_30.purple },
    ["@keyword.return"] = { fg = M.base_30.purple },
    ["@keyword.conditional"] = { fg = M.base_30.purple },
    ["@keyword.storage"] = { fg = M.base_30.purple },
    ["@keyword.repeat"] = { fg = M.base_30.purple },
    ["@keyword.operator"] = { fg = M.base_30.pink },
    ["@type"] = { fg = M.base_30.nord_blue },
    ["@type.builtin"] = { fg = M.base_30.nord_blue },
    ["@boolean"] = { fg = M.base_30.purple },
    ["@constant"] = { fg = M.base_30.orange },
    ["@constant.builtin"] = { fg = M.base_30.orange },
    ["@number"] = { fg = M.base_30.orange },
    ["@tag"] = { fg = M.base_30.pink },
    ["@tag.attribute"] = { fg = M.base_30.orange },
    ["@operator"] = { fg = M.base_30.pink },
    ["@property"] = { fg = M.base_30.white },
    ["@function.call"] = { fg = M.base_30.nord_blue },
    ["@constructor"] = { fg = M.base_30.nord_blue },
  },
  syntax = {
    Boolean = { fg = M.base_30.purple },
    Constant = { fg = M.base_30.orange },
    Number = { fg = M.base_30.orange },
    Float = { fg = M.base_30.orange },
    Type = { fg = M.base_30.nord_blue },
    StorageClass = { fg = M.base_30.purple },
    Function = { fg = M.base_30.nord_blue },
    String = { fg = M.base_30.green },
    Keyword = { fg = M.base_30.purple },
    Conditional = { fg = M.base_30.purple },
    Tag = { fg = M.base_30.pink },
    Operator = { fg = M.base_30.pink },
    Identifier = { fg = M.base_30.white },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "dracula")
return M
