-- Dracula Soft — ported from dracula-theme.theme-dracula VS Code
local M = {}

M.base_30 = {
  white          = "#f6f6f4",
  darker_black   = "#1e2030",
  black          = "#282A36",
  black2         = "#2e3040",
  one_bg         = "#343746",
  one_bg2        = "#3e4052",
  one_bg3        = "#44475A",
  grey           = "#7b7f8b",
  grey_fg        = "#7b7f8b",
  grey_fg2       = "#9a9eaa",
  light_grey     = "#c8cacc",
  red            = "#ee6666",
  baby_pink      = "#f286c4",
  pink           = "#f286c4",
  line           = "#44475A",
  green          = "#62e884",
  vibrant_green  = "#7aee96",
  nord_blue      = "#97e1f1",
  blue           = "#97e1f1",
  yellow         = "#e7ee98",
  sun            = "#edf2aa",
  purple         = "#bf9eee",
  dark_purple    = "#a67de0",
  teal           = "#97e1f1",
  orange         = "#FFB86C",
  cyan           = "#97e1f1",
  statusline_bg  = "#21222C",
  lightbg        = "#343746",
  pmenu_bg       = "#bf9eee",
  folder_bg      = "#97e1f1",
}

M.base_16 = {
  base00 = "#282A36",
  base01 = "#343746",
  base02 = "#3e4052",
  base03 = "#44475A",
  base04 = "#7b7f8b",
  base05 = "#f6f6f4",
  base06 = "#f6f6f4",
  base07 = "#FFFFFF",
  base08 = "#f286c4",
  base09 = "#FFB86C",
  base0A = "#bf9eee",
  base0B = "#62e884",
  base0C = "#97e1f1",
  base0D = "#97e1f1",
  base0E = "#bf9eee",
  base0F = "#e7ee98",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_30.white },
    ["@variable.builtin"] = { fg = M.base_30.pink },
    ["@variable.parameter"] = { fg = M.base_30.orange },
    ["@keyword"] = { fg = M.base_30.purple },
    ["@keyword.function"] = { fg = M.base_30.purple },
    ["@keyword.return"] = { fg = M.base_30.purple },
    ["@keyword.conditional"] = { fg = M.base_30.purple },
    ["@keyword.storage"] = { fg = M.base_30.purple },
    ["@keyword.repeat"] = { fg = M.base_30.purple },
    ["@keyword.operator"] = { fg = M.base_30.pink },
    ["@type"] = { fg = M.base_30.nord_blue },
    ["@type.builtin"] = { fg = M.base_30.nord_blue },
    ["@boolean"] = { fg = M.base_30.purple },
    ["@constant"] = { fg = M.base_30.orange },
    ["@constant.builtin"] = { fg = M.base_30.orange },
    ["@number"] = { fg = M.base_30.orange },
    ["@tag"] = { fg = M.base_30.pink },
    ["@tag.attribute"] = { fg = M.base_30.orange },
    ["@operator"] = { fg = M.base_30.pink },
    ["@property"] = { fg = M.base_30.white },
    ["@function.call"] = { fg = M.base_30.nord_blue },
    ["@constructor"] = { fg = M.base_30.nord_blue },
  },
  syntax = {
    Boolean = { fg = M.base_30.purple },
    Constant = { fg = M.base_30.orange },
    Number = { fg = M.base_30.orange },
    Float = { fg = M.base_30.orange },
    Type = { fg = M.base_30.nord_blue },
    StorageClass = { fg = M.base_30.purple },
    Function = { fg = M.base_30.nord_blue },
    String = { fg = M.base_30.green },
    Keyword = { fg = M.base_30.purple },
    Conditional = { fg = M.base_30.purple },
    Tag = { fg = M.base_30.pink },
    Operator = { fg = M.base_30.pink },
    Identifier = { fg = M.base_30.white },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "dracula_soft")
return M
