-- Mayukai Mono — ported from gulajavaministudio.mayukaithemevsc VS Code
local M = {}

M.base_30 = {
  white          = "#cbcebc",
  darker_black   = "#0e121d",
  black          = "#141824",
  black2         = "#1a1e2a",
  one_bg         = "#222632",
  one_bg2        = "#2e3240",
  one_bg3        = "#3d424d",
  grey           = "#5c6773",
  grey_fg        = "#5c6773",
  grey_fg2       = "#7a8490",
  light_grey     = "#b3b1ad",
  red            = "#ff3333",
  baby_pink      = "#FF6188",
  pink           = "#fc4085",
  line           = "#1a1e2a",
  green          = "#A9DC76",
  vibrant_green  = "#95e6cb",
  nord_blue      = "#78DCE8",
  blue           = "#78DCE8",
  yellow         = "#FFD866",
  sun            = "#e6b450",
  purple         = "#d4bfff",
  dark_purple    = "#C39AC9",
  teal           = "#9CD1BB",
  orange         = "#fc9867",
  cyan           = "#78DCE8",
  statusline_bg  = "#0e121d",
  lightbg        = "#222632",
  pmenu_bg       = "#d4bfff",
  folder_bg      = "#78DCE8",
}

M.base_16 = {
  base00 = "#141824",
  base01 = "#222632",
  base02 = "#2e3240",
  base03 = "#3d424d",
  base04 = "#5c6773",
  base05 = "#cbcebc",
  base06 = "#cbcebc",
  base07 = "#ffffff",
  base08 = "#FF6188",
  base09 = "#fc9867",
  base0A = "#ffa759",
  base0B = "#A9DC76",
  base0C = "#9CD1BB",
  base0D = "#f28779",
  base0E = "#ffcc66",
  base0F = "#d4bfff",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_30.white },
    ["@variable.member"] = { fg = M.base_30.baby_pink },
    ["@variable.builtin"] = { fg = M.base_30.orange },
    ["@keyword.function"] = { fg = M.base_30.sun },
    ["@keyword.return"] = { fg = M.base_30.yellow },
    ["@keyword.conditional"] = { fg = M.base_30.yellow },
    ["@keyword.storage"] = { fg = M.base_30.orange },
    ["@keyword.repeat"] = { fg = M.base_30.yellow },
    ["@keyword.operator"] = { fg = M.base_30.baby_pink },
    ["@type"] = { fg = M.base_30.teal },
    ["@type.builtin"] = { fg = M.base_30.teal },
    ["@variable.parameter"] = { fg = M.base_30.orange },
    ["@boolean"] = { fg = M.base_30.purple },
    ["@constant.builtin"] = { fg = M.base_30.red },
    ["@tag"] = { fg = M.base_30.pink },
    ["@tag.attribute"] = { fg = M.base_30.sun },
    ["@operator"] = { fg = M.base_30.light_grey },
    ["@property"] = { fg = M.base_30.white },
    ["@function.call"] = { fg = M.base_30.yellow },
  },
  syntax = {
    Boolean = { fg = M.base_30.purple },
    Type = { fg = M.base_30.teal },
    StorageClass = { fg = M.base_30.orange },
    Function = { fg = M.base_30.red },
    String = { fg = M.base_30.green },
    Constant = { fg = M.base_30.cyan },
    Keyword = { fg = M.base_30.yellow },
    Conditional = { fg = M.base_30.yellow },
    Tag = { fg = M.base_30.pink },
    Identifier = { fg = M.base_30.orange },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "mayukai_mono")
return M
