-- Styx Dracula — ported from hshhrr.styx VS Code
-- Minimalist dark theme w/ Dracula palette, pure black bg
local M = {}

M.base_30 = {
  white          = "#DADDE6",
  darker_black   = "#0a0a0a",
  black          = "#000000",
  black2         = "#0c0c0c",
  one_bg         = "#141414",
  one_bg2        = "#1e1e1e",
  one_bg3        = "#2a2a2a",
  grey           = "#6272A4",
  grey_fg        = "#6272A4",
  grey_fg2       = "#8890b8",
  light_grey     = "#DADDE6",
  red            = "#FF5555",
  baby_pink      = "#FF80AB",
  pink           = "#FF80AB",
  line           = "#0c0c0c",
  green          = "#69F0AE",
  vibrant_green  = "#69F0AE",
  nord_blue      = "#8BE9FD",
  blue           = "#8BE9FD",
  yellow         = "#FFF59D",
  sun            = "#FFF59D",
  purple         = "#B388FF",
  dark_purple    = "#9970e0",
  teal           = "#8BE9FD",
  orange         = "#FFB74D",
  cyan           = "#8BE9FD",
  statusline_bg  = "#0a0a0a",
  lightbg        = "#141414",
  pmenu_bg       = "#B388FF",
  folder_bg      = "#8BE9FD",
}

M.base_16 = {
  base00 = "#000000",
  base01 = "#141414",
  base02 = "#1e1e1e",
  base03 = "#2a2a2a",
  base04 = "#6272A4",
  base05 = "#DADDE6",
  base06 = "#DADDE6",
  base07 = "#ffffff",
  base08 = "#FFB74D",
  base09 = "#FFB74D",
  base0A = "#FF80AB",
  base0B = "#FFF59D",
  base0C = "#69F0AE",
  base0D = "#8BE9FD",
  base0E = "#FF80AB",
  base0F = "#B388FF",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_30.white },
    ["@variable.builtin"] = { fg = M.base_30.white },
    ["@variable.parameter"] = { fg = M.base_30.orange },
    ["@variable.member"] = { fg = M.base_30.white },
    ["@keyword"] = { fg = M.base_30.baby_pink },
    ["@keyword.function"] = { fg = M.base_30.baby_pink },
    ["@keyword.return"] = { fg = M.base_30.baby_pink },
    ["@keyword.conditional"] = { fg = M.base_30.baby_pink },
    ["@keyword.storage"] = { fg = M.base_30.baby_pink },
    ["@keyword.repeat"] = { fg = M.base_30.baby_pink },
    ["@keyword.operator"] = { fg = M.base_30.orange },
    ["@type"] = { fg = M.base_30.nord_blue },
    ["@type.builtin"] = { fg = M.base_30.nord_blue },
    ["@boolean"] = { fg = M.base_30.yellow },
    ["@constant"] = { fg = M.base_30.yellow },
    ["@constant.builtin"] = { fg = M.base_30.yellow },
    ["@number"] = { fg = M.base_30.yellow },
    ["@string"] = { fg = M.base_30.yellow },
    ["@tag"] = { fg = M.base_30.baby_pink },
    ["@tag.attribute"] = { fg = M.base_30.orange },
    ["@operator"] = { fg = M.base_30.baby_pink },
    ["@property"] = { fg = M.base_30.white },
    ["@function"] = { fg = M.base_30.nord_blue },
    ["@function.call"] = { fg = M.base_30.nord_blue },
  },
  syntax = {
    Boolean = { fg = M.base_30.yellow },
    Constant = { fg = M.base_30.yellow },
    Number = { fg = M.base_30.yellow },
    Float = { fg = M.base_30.yellow },
    String = { fg = M.base_30.yellow },
    Type = { fg = M.base_30.nord_blue },
    StorageClass = { fg = M.base_30.baby_pink },
    Function = { fg = M.base_30.nord_blue },
    Keyword = { fg = M.base_30.baby_pink },
    Conditional = { fg = M.base_30.baby_pink },
    Tag = { fg = M.base_30.baby_pink },
    Operator = { fg = M.base_30.orange },
    Identifier = { fg = M.base_30.white },
    PreProc = { fg = M.base_30.baby_pink },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "styx_dracula")
return M
