-- Styx Fleet — ported from hshhrr.styx VS Code
-- Minimalist dark theme, pure black bg, colored accents on keywords/numbers/params
local M = {}

M.base_30 = {
  white          = "#DADDE6",
  darker_black   = "#0a0a0a",
  black          = "#000000",
  black2         = "#0c0c0c",
  one_bg         = "#141414",
  one_bg2        = "#1e1e1e",
  one_bg3        = "#2a2a2a",
  grey           = "#767676",
  grey_fg        = "#767676",
  grey_fg2       = "#999999",
  light_grey     = "#DADDE6",
  red            = "#FF5555",
  baby_pink      = "#CC7C8A",
  pink           = "#E394DC",
  line           = "#0c0c0c",
  green          = "#A8CC7C",
  vibrant_green  = "#70CCA0",
  nord_blue      = "#82D2CE",
  blue           = "#82D2CE",
  yellow         = "#E6D58A",
  sun            = "#E6D58A",
  purple         = "#AF9CFF",
  dark_purple    = "#8a77e0",
  teal           = "#82D2CE",
  orange         = "#E09B70",
  cyan           = "#82D2CE",
  statusline_bg  = "#0a0a0a",
  lightbg        = "#141414",
  pmenu_bg       = "#AF9CFF",
  folder_bg      = "#82D2CE",
}

M.base_16 = {
  base00 = "#000000",
  base01 = "#141414",
  base02 = "#1e1e1e",
  base03 = "#2a2a2a",
  base04 = "#767676",
  base05 = "#DADDE6",
  base06 = "#DADDE6",
  base07 = "#ffffff",
  base08 = "#E09B70",
  base09 = "#E6D58A",
  base0A = "#82D2CE",
  base0B = "#A8CC7C",
  base0C = "#70CCA0",
  base0D = "#ECEFF1",
  base0E = "#E394DC",
  base0F = "#AF9CFF",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_30.white },
    ["@variable.builtin"] = { fg = M.base_30.baby_pink },
    ["@variable.parameter"] = { fg = M.base_30.orange },
    ["@variable.member"] = { fg = M.base_30.white },
    ["@keyword"] = { fg = M.base_30.nord_blue },
    ["@keyword.function"] = { fg = M.base_30.nord_blue },
    ["@keyword.return"] = { fg = M.base_30.nord_blue },
    ["@keyword.conditional"] = { fg = M.base_30.nord_blue },
    ["@keyword.storage"] = { fg = M.base_30.nord_blue },
    ["@keyword.repeat"] = { fg = M.base_30.nord_blue },
    ["@keyword.operator"] = { fg = M.base_30.orange },
    ["@type"] = { fg = M.base_30.white },
    ["@type.builtin"] = { fg = M.base_30.white },
    ["@boolean"] = { fg = M.base_30.yellow },
    ["@constant"] = { fg = M.base_30.yellow },
    ["@constant.builtin"] = { fg = M.base_30.yellow },
    ["@number"] = { fg = M.base_30.yellow },
    ["@tag"] = { fg = M.base_30.pink },
    ["@tag.attribute"] = { fg = M.base_30.yellow },
    ["@operator"] = { fg = M.base_30.pink },
    ["@property"] = { fg = M.base_30.white },
    ["@function"] = { fg = M.base_30.white },
    ["@function.call"] = { fg = M.base_30.white },
  },
  syntax = {
    Boolean = { fg = M.base_30.yellow },
    Constant = { fg = M.base_30.yellow },
    Number = { fg = M.base_30.yellow },
    Float = { fg = M.base_30.yellow },
    Type = { fg = M.base_30.white },
    StorageClass = { fg = M.base_30.nord_blue },
    Function = { fg = M.base_30.white },
    String = { fg = M.base_30.green },
    Keyword = { fg = M.base_30.nord_blue },
    Conditional = { fg = M.base_30.nord_blue },
    Tag = { fg = M.base_30.pink },
    Operator = { fg = M.base_30.orange },
    Identifier = { fg = M.base_30.white },
    PreProc = { fg = M.base_30.nord_blue },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "styx_fleet")
return M
